### PR TITLE
Redesign the web views

### PR DESCRIPTION
**Pull request by relekang**
### Todo
- [x] Login screen
- [x] 404
- [x] Error pages

screenshot 2015-02-19 09 47 06
screenshot 2015-02-19 09 46 52

### CODE REVIEW

**Comment by ekmartin** [comment]
Looks great!

**Comment by relekang** [comment]
### 404:
screenshot 2015-02-20 13 06 34

**Comment by relekang** [comment]
### Login:
screenshot 2015-02-20 13 29 37

**Comment by ekmartin** [comment]
:tada:

**Pull request merged**
